# Preface {.unnumbered}

Welcome to How to Learn to Code!!

We are an organization that hopes to make learning to program approachable, accessible, and effective. We want to improve rigor and reproducibility in science by providing programming resources and experiences to scientists and professionals in all levels of their careers. Our classes are small-group based courses with a teacher:student ratio that allows the students to learn dynamically and independently. During classes, students are able to follow along with the teacher leading the instruction, or work with one of our floating teachers to troubleshoot or to better understand their own code.

This is our curriculum for learning R programming in the context of data analysis. Our curriculum development team has worked tirelessly to develop this new curriculum for the Summer of 2024. We are constantly improving and updating our curricula, so if you're interested in contributing or have suggestions, please visit <https://howtolearntocode.web.unc.edu/> for our most up-to-date contact information. If you have gotten to our Class 7 over Github, or are proficient in Github yourself, feel free to submit an issue or pull request at <https://github.com/How-to-Learn-to-Code/Rclass-DataScience>.

| Class Day |                   Topic                    |                Link                |
|:---------:|:------------------------------------------:|:----------------------------------:|
|     0     |      Welcome to How to Learn to Code!      |     [Introduction](class0.qmd)     |
|     1     |              R Coding Basics               |   [Coding Basics 1](class1.qmd)    |
|     2     |           Applying Coding Basics           |   [Coding Basics 2](class2.qmd)    |
|     3     |            Let's Get Plotting!             | [Data Visualization 1](class3.qmd) |
|     4     |       Applying Visualization Methods       | [Data Vizualization 2](class4.qmd) |
|     5     |           Data Wrangling Basics            |   [Data Wrangling 1](class5.qmd)   |
|     6     | Data Wrangling with Real Experimental Data |   [Data Wrangling 2](class6.qmd)   |
|     7     |      Running a Reproducible Analysis       |      [Project 1](class7.qmd)       |
|     8     |       Practicing on Real World Data        |      [Project 2](class8.qmd)       |

: Table of Contents
