name: Custom GitHub Pages Build and Deploy

on:
  push:
    branches:
      - test  # or any branch you want to test on
  workflow_dispatch:   # optional, for manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Restore R dependencies using renv (if you're using renv)
      - name: Restore R dependencies with renv
        run: Rscript -e 'renv::restore()'
      
      # Render your Quarto site
      - name: Render site with Quarto
        run: quarto render

      # Debug step: List files in the output directory to verify rendering
      - name: List rendered files
        run: ls -la docs

      # Deploy the rendered site to GitHub Pages (using the correct output directory)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
